transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/DE0_LT24_SOPC.v}
vlog -vlog01compat -work work +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/ip/LED_Controller {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/ip/LED_Controller/LED_Controller.v}
vlog -vlog01compat -work work +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/ip/LT24_Controller {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/ip/LT24_Controller/LT24_Controller.v}
vlog -vlog01compat -work work +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/DE0_LT24_SOPC.v}
vlog -vlog01compat -work work +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/LT24_buffer.v}
vlib DE0_LT24_SOPC
vmap DE0_LT24_SOPC DE0_LT24_SOPC
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_avalon_st_adapter_007.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_pic_mem.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_background_mem.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_TIMER.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_SDRAM.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/LT24_interface_irq.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_LT24_TOUCH_SPI.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_LT24_TOUCH_PENIRQ_N.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_LT24_TOUCH_BUSY.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_LT24_LCD_RSTN.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_KEY.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_JTAG_UART.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_ALT_PLL.v}
vlog -sv -work work +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/MySPI.sv}
vlog -sv -work work +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_Nano.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_irq_clock_crosser.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_irq_mapper.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_avalon_st_adapter_007_error_adapter_0.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_std_synchronizer_nocut.v}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_rsp_mux_001.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_rsp_demux_005.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_rsp_demux_002.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_cmd_mux_005.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_merlin_burst_adapter_uncmpr.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_merlin_traffic_limiter.sv}
vlog -vlog01compat -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_router_015.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_router_009.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_router_007.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_router_002.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_router_001.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/DE0_LT24_SOPC_mm_interconnect_0_router.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work DE0_LT24_SOPC +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/DE0_LT24_SOPC/synthesis/submodules/MyCycloneSPI.sv}

vlog -sv -work work +incdir+/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student {/home/obronchain/git_projects/ELEC2103/Electronic/DE0_LT24_student/testbench.sv}

vsim -t 1ps -L altera_ver -L lpm_ver -L sgate_ver -L altera_mf_ver -L altera_lnsim_ver -L cycloneive_ver -L rtl_work -L work -L DE0_LT24_SOPC -voptargs="+acc"  testbench

add wave *
view structure
view signals
run 100 ms
