# TCL File Generated by Component Editor 15.0
# Mon Mar 21 15:14:39 CET 2016
# DO NOT MODIFY


# 
# cycloneSPI "cycloneSPI" v1.0
#  2016.03.21.15:14:39
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module cycloneSPI
# 
set_module_property DESCRIPTION ""
set_module_property NAME cycloneSPI
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME cycloneSPI
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL MyCycloneSPI
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file MyCycloneSPI.sv SYSTEM_VERILOG PATH MyCycloneSPI.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter A_Config STD_LOGIC_VECTOR 0
set_parameter_property A_Config DEFAULT_VALUE 0
set_parameter_property A_Config DISPLAY_NAME A_Config
set_parameter_property A_Config TYPE STD_LOGIC_VECTOR
set_parameter_property A_Config UNITS None
set_parameter_property A_Config ALLOWED_RANGES 0:255
set_parameter_property A_Config HDL_PARAMETER true
add_parameter RetreiveAddr STD_LOGIC_VECTOR 1
set_parameter_property RetreiveAddr DEFAULT_VALUE 1
set_parameter_property RetreiveAddr DISPLAY_NAME RetreiveAddr
set_parameter_property RetreiveAddr TYPE STD_LOGIC_VECTOR
set_parameter_property RetreiveAddr UNITS None
set_parameter_property RetreiveAddr ALLOWED_RANGES 0:255
set_parameter_property RetreiveAddr HDL_PARAMETER true
add_parameter Counter STD_LOGIC_VECTOR 2
set_parameter_property Counter DEFAULT_VALUE 2
set_parameter_property Counter DISPLAY_NAME Counter
set_parameter_property Counter TYPE STD_LOGIC_VECTOR
set_parameter_property Counter UNITS None
set_parameter_property Counter ALLOWED_RANGES 0:255
set_parameter_property Counter HDL_PARAMETER true
add_parameter PosX STD_LOGIC_VECTOR 3
set_parameter_property PosX DEFAULT_VALUE 3
set_parameter_property PosX DISPLAY_NAME PosX
set_parameter_property PosX TYPE STD_LOGIC_VECTOR
set_parameter_property PosX UNITS None
set_parameter_property PosX ALLOWED_RANGES 0:255
set_parameter_property PosX HDL_PARAMETER true
add_parameter PosY STD_LOGIC_VECTOR 4
set_parameter_property PosY DEFAULT_VALUE 4
set_parameter_property PosY DISPLAY_NAME PosY
set_parameter_property PosY TYPE STD_LOGIC_VECTOR
set_parameter_property PosY UNITS None
set_parameter_property PosY ALLOWED_RANGES 0:255
set_parameter_property PosY HDL_PARAMETER true
add_parameter ImagePixel_R STD_LOGIC_VECTOR 18
set_parameter_property ImagePixel_R DEFAULT_VALUE 18
set_parameter_property ImagePixel_R DISPLAY_NAME ImagePixel_R
set_parameter_property ImagePixel_R TYPE STD_LOGIC_VECTOR
set_parameter_property ImagePixel_R UNITS None
set_parameter_property ImagePixel_R ALLOWED_RANGES 0:255
set_parameter_property ImagePixel_R HDL_PARAMETER true
add_parameter ImagePixel_G STD_LOGIC_VECTOR 19
set_parameter_property ImagePixel_G DEFAULT_VALUE 19
set_parameter_property ImagePixel_G DISPLAY_NAME ImagePixel_G
set_parameter_property ImagePixel_G TYPE STD_LOGIC_VECTOR
set_parameter_property ImagePixel_G UNITS None
set_parameter_property ImagePixel_G ALLOWED_RANGES 0:255
set_parameter_property ImagePixel_G HDL_PARAMETER true
add_parameter ImagePixel_B STD_LOGIC_VECTOR 20
set_parameter_property ImagePixel_B DEFAULT_VALUE 20
set_parameter_property ImagePixel_B DISPLAY_NAME ImagePixel_B
set_parameter_property ImagePixel_B TYPE STD_LOGIC_VECTOR
set_parameter_property ImagePixel_B UNITS None
set_parameter_property ImagePixel_B ALLOWED_RANGES 0:255
set_parameter_property ImagePixel_B HDL_PARAMETER true
add_parameter A_Led70 STD_LOGIC_VECTOR 22
set_parameter_property A_Led70 DEFAULT_VALUE 22
set_parameter_property A_Led70 DISPLAY_NAME A_Led70
set_parameter_property A_Led70 TYPE STD_LOGIC_VECTOR
set_parameter_property A_Led70 UNITS None
set_parameter_property A_Led70 ALLOWED_RANGES 0:255
set_parameter_property A_Led70 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avs_s0
# 
add_interface avs_s0 avalon end
set_interface_property avs_s0 addressUnits WORDS
set_interface_property avs_s0 associatedClock clock
set_interface_property avs_s0 associatedReset reset
set_interface_property avs_s0 bitsPerSymbol 8
set_interface_property avs_s0 bridgedAddressOffset 0
set_interface_property avs_s0 burstOnBurstBoundariesOnly false
set_interface_property avs_s0 burstcountUnits WORDS
set_interface_property avs_s0 explicitAddressSpan 0
set_interface_property avs_s0 holdTime 0
set_interface_property avs_s0 linewrapBursts false
set_interface_property avs_s0 maximumPendingReadTransactions 0
set_interface_property avs_s0 maximumPendingWriteTransactions 0
set_interface_property avs_s0 readLatency 0
set_interface_property avs_s0 readWaitTime 1
set_interface_property avs_s0 setupTime 0
set_interface_property avs_s0 timingUnits Cycles
set_interface_property avs_s0 writeWaitTime 0
set_interface_property avs_s0 ENABLED true
set_interface_property avs_s0 EXPORT_OF ""
set_interface_property avs_s0 PORT_NAME_MAP ""
set_interface_property avs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property avs_s0 SVD_ADDRESS_GROUP ""

add_interface_port avs_s0 avs_s0_address address Input 8
add_interface_port avs_s0 avs_s0_read read Input 1
add_interface_port avs_s0 avs_s0_readdata readdata Output 32
add_interface_port avs_s0 avs_s0_write write Input 1
add_interface_port avs_s0 avs_s0_writedata writedata Input 32
add_interface_port avs_s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment avs_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point ins_irq0
# 
add_interface ins_irq0 interrupt end
set_interface_property ins_irq0 associatedAddressablePoint avs_s0
set_interface_property ins_irq0 associatedClock clock
set_interface_property ins_irq0 associatedReset reset
set_interface_property ins_irq0 bridgedReceiverOffset 0
set_interface_property ins_irq0 bridgesToReceiver ""
set_interface_property ins_irq0 ENABLED true
set_interface_property ins_irq0 EXPORT_OF ""
set_interface_property ins_irq0 PORT_NAME_MAP ""
set_interface_property ins_irq0 CMSIS_SVD_VARIABLES ""
set_interface_property ins_irq0 SVD_ADDRESS_GROUP ""

add_interface_port ins_irq0 ins_irq0_irq irq Output 1


# 
# connection point SPI_interface
# 
add_interface SPI_interface conduit end
set_interface_property SPI_interface associatedClock clock
set_interface_property SPI_interface associatedReset ""
set_interface_property SPI_interface ENABLED true
set_interface_property SPI_interface EXPORT_OF ""
set_interface_property SPI_interface PORT_NAME_MAP ""
set_interface_property SPI_interface CMSIS_SVD_VARIABLES ""
set_interface_property SPI_interface SVD_ADDRESS_GROUP ""

add_interface_port SPI_interface Config Config Output 8
add_interface_port SPI_interface SPI_CS SPI_CS Input 1
add_interface_port SPI_interface SPI_SDI SPI_SDI Input 1
add_interface_port SPI_interface SPI_SDO SPI_SDO Output 1
add_interface_port SPI_interface SPI_clk SPI_clk Input 1
add_interface_port SPI_interface data_out data_out Output 8
add_interface_port SPI_interface data_out_enable data_out_enable Output 1
add_interface_port SPI_interface spi_irq spi_irq Output 1

