# TCL File Generated by Component Editor 15.0
# Fri Mar 18 14:09:26 CET 2016
# DO NOT MODIFY


# 
# mtl_interface_irq "mtl_interface_irq" v1.0
#  2016.03.18.14:09:26
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module mtl_interface_irq
# 
set_module_property DESCRIPTION ""
set_module_property NAME mtl_interface_irq
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mtl_interface_irq
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mtl_interface_irq
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mtl_interface_irq.v VERILOG PATH mtl_interface_irq.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter mtl_reset_addr STD_LOGIC_VECTOR 0
set_parameter_property mtl_reset_addr DEFAULT_VALUE 0
set_parameter_property mtl_reset_addr DISPLAY_NAME mtl_reset_addr
set_parameter_property mtl_reset_addr TYPE STD_LOGIC_VECTOR
set_parameter_property mtl_reset_addr UNITS None
set_parameter_property mtl_reset_addr ALLOWED_RANGES 0:7
set_parameter_property mtl_reset_addr HDL_PARAMETER true
add_parameter mtl_mode_addr STD_LOGIC_VECTOR 1
set_parameter_property mtl_mode_addr DEFAULT_VALUE 1
set_parameter_property mtl_mode_addr DISPLAY_NAME mtl_mode_addr
set_parameter_property mtl_mode_addr TYPE STD_LOGIC_VECTOR
set_parameter_property mtl_mode_addr UNITS None
set_parameter_property mtl_mode_addr ALLOWED_RANGES 0:7
set_parameter_property mtl_mode_addr HDL_PARAMETER true
add_parameter mtl_counter_addr STD_LOGIC_VECTOR 2
set_parameter_property mtl_counter_addr DEFAULT_VALUE 2
set_parameter_property mtl_counter_addr DISPLAY_NAME mtl_counter_addr
set_parameter_property mtl_counter_addr TYPE STD_LOGIC_VECTOR
set_parameter_property mtl_counter_addr UNITS None
set_parameter_property mtl_counter_addr ALLOWED_RANGES 0:7
set_parameter_property mtl_counter_addr HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avs_s0
# 
add_interface avs_s0 avalon end
set_interface_property avs_s0 addressUnits WORDS
set_interface_property avs_s0 associatedClock clock
set_interface_property avs_s0 associatedReset reset
set_interface_property avs_s0 bitsPerSymbol 8
set_interface_property avs_s0 bridgedAddressOffset 0
set_interface_property avs_s0 burstOnBurstBoundariesOnly false
set_interface_property avs_s0 burstcountUnits WORDS
set_interface_property avs_s0 explicitAddressSpan 0
set_interface_property avs_s0 holdTime 0
set_interface_property avs_s0 linewrapBursts false
set_interface_property avs_s0 maximumPendingReadTransactions 0
set_interface_property avs_s0 maximumPendingWriteTransactions 0
set_interface_property avs_s0 readLatency 0
set_interface_property avs_s0 readWaitTime 1
set_interface_property avs_s0 setupTime 0
set_interface_property avs_s0 timingUnits Cycles
set_interface_property avs_s0 writeWaitTime 0
set_interface_property avs_s0 ENABLED true
set_interface_property avs_s0 EXPORT_OF ""
set_interface_property avs_s0 PORT_NAME_MAP ""
set_interface_property avs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property avs_s0 SVD_ADDRESS_GROUP ""

add_interface_port avs_s0 avs_s0_address address Input 8
add_interface_port avs_s0 avs_s0_read read Input 1
add_interface_port avs_s0 avs_s0_readdata readdata Output 32
add_interface_port avs_s0 avs_s0_write write Input 1
add_interface_port avs_s0 avs_s0_writedata writedata Input 32
add_interface_port avs_s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment avs_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point ins_irq0
# 
add_interface ins_irq0 interrupt end
set_interface_property ins_irq0 associatedAddressablePoint avs_s0
set_interface_property ins_irq0 associatedClock clock
set_interface_property ins_irq0 associatedReset reset
set_interface_property ins_irq0 bridgedReceiverOffset 0
set_interface_property ins_irq0 bridgesToReceiver ""
set_interface_property ins_irq0 ENABLED true
set_interface_property ins_irq0 EXPORT_OF ""
set_interface_property ins_irq0 PORT_NAME_MAP ""
set_interface_property ins_irq0 CMSIS_SVD_VARIABLES ""
set_interface_property ins_irq0 SVD_ADDRESS_GROUP ""

add_interface_port ins_irq0 ins_irq0_irq irq Output 1


# 
# connection point mtl_intreface
# 
add_interface mtl_intreface conduit end
set_interface_property mtl_intreface associatedClock clock
set_interface_property mtl_intreface associatedReset ""
set_interface_property mtl_intreface ENABLED true
set_interface_property mtl_intreface EXPORT_OF ""
set_interface_property mtl_intreface PORT_NAME_MAP ""
set_interface_property mtl_intreface CMSIS_SVD_VARIABLES ""
set_interface_property mtl_intreface SVD_ADDRESS_GROUP ""

add_interface_port mtl_intreface mtl_counter mtl_counter Input 32
add_interface_port mtl_intreface mtl_irq mtl_irq Input 1
add_interface_port mtl_intreface mtl_reset mtl_reset Output 1
add_interface_port mtl_intreface mtl_mode mtl_mode Output 4

