# TCL File Generated by Component Editor 15.1
# Thu Feb 25 11:27:16 CET 2016
# DO NOT MODIFY


# 
# cycloneSPI "cycloneSPI" v1.0
# Group7 2016.02.25.11:27:16
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module cycloneSPI
# 
set_module_property DESCRIPTION ""
set_module_property NAME cycloneSPI
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR Group7
set_module_property DISPLAY_NAME cycloneSPI
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL MyCycloneSPI
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file MyCycloneSPI.sv SYSTEM_VERILOG PATH DE0_LT24_SOPC/synthesis/submodules/MyCycloneSPI.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock ""
set_interface_property reset_sink synchronousEdges NONE
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point SPI_interface
# 
add_interface SPI_interface conduit end
set_interface_property SPI_interface associatedClock clock_sink
set_interface_property SPI_interface associatedReset ""
set_interface_property SPI_interface ENABLED true
set_interface_property SPI_interface EXPORT_OF ""
set_interface_property SPI_interface PORT_NAME_MAP ""
set_interface_property SPI_interface CMSIS_SVD_VARIABLES ""
set_interface_property SPI_interface SVD_ADDRESS_GROUP ""

add_interface_port SPI_interface SPI_clk SPI_clk Input 1
add_interface_port SPI_interface SPI_CS SPI_CS Input 1
add_interface_port SPI_interface SPI_SDI SPI_SDI Input 1
add_interface_port SPI_interface SPI_SDO SPI_SDO Output 1
add_interface_port SPI_interface data_out data_out Output 8
add_interface_port SPI_interface data_out_enable data_out_enable Output 1
add_interface_port SPI_interface Config config Output 8
add_interface_port SPI_interface spi_irq spi_irq Output 1


# 
# connection point avs_s0
# 
add_interface avs_s0 avalon end
set_interface_property avs_s0 addressUnits WORDS
set_interface_property avs_s0 associatedClock clock_sink
set_interface_property avs_s0 associatedReset reset_sink
set_interface_property avs_s0 bitsPerSymbol 8
set_interface_property avs_s0 bridgedAddressOffset 0
set_interface_property avs_s0 burstOnBurstBoundariesOnly false
set_interface_property avs_s0 burstcountUnits WORDS
set_interface_property avs_s0 explicitAddressSpan 0
set_interface_property avs_s0 holdTime 0
set_interface_property avs_s0 linewrapBursts false
set_interface_property avs_s0 maximumPendingReadTransactions 0
set_interface_property avs_s0 maximumPendingWriteTransactions 0
set_interface_property avs_s0 readLatency 0
set_interface_property avs_s0 readWaitTime 1
set_interface_property avs_s0 setupTime 0
set_interface_property avs_s0 timingUnits Cycles
set_interface_property avs_s0 writeWaitTime 0
set_interface_property avs_s0 ENABLED true
set_interface_property avs_s0 EXPORT_OF ""
set_interface_property avs_s0 PORT_NAME_MAP ""
set_interface_property avs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property avs_s0 SVD_ADDRESS_GROUP ""

add_interface_port avs_s0 avs_s0_address address Input 8
add_interface_port avs_s0 avs_s0_read read Input 1
add_interface_port avs_s0 avs_s0_readdata readdata Output 32
add_interface_port avs_s0 avs_s0_write write Input 1
add_interface_port avs_s0 avs_s0_writedata writedata Input 32
add_interface_port avs_s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment avs_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ins_irq0
# 
add_interface ins_irq0 interrupt end
set_interface_property ins_irq0 associatedAddressablePoint avs_s0
set_interface_property ins_irq0 associatedClock clock_sink
set_interface_property ins_irq0 bridgedReceiverOffset 0
set_interface_property ins_irq0 bridgesToReceiver ""
set_interface_property ins_irq0 ENABLED true
set_interface_property ins_irq0 EXPORT_OF ""
set_interface_property ins_irq0 PORT_NAME_MAP ""
set_interface_property ins_irq0 CMSIS_SVD_VARIABLES ""
set_interface_property ins_irq0 SVD_ADDRESS_GROUP ""

add_interface_port ins_irq0 ins_irq0_irq irq Output 1

